{% set version = "0.0.18" %}
{% set posix = 'm2-' if win else '' %}

package:
  name: r-kit
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/kit_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/kit/kit_{{ version }}.tar.gz
  sha256: 181e2cccd0e6d54e30995f0d4f529dc73f0ff3d34fbfe649edadb397a05d6147

build:
  number: 1
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ compiler('c') }}              # [not win]
    - {{ stdlib("c") }}                # [not win]
    - {{ compiler('m2w64_c') }}        # [win]
    - {{ stdlib("c") }}                # [win]
    - {{ posix }}filesystem        # [win]
    - {{ posix }}sed               # [win]
    - {{ posix }}grep              # [win]
    - {{ posix }}autoconf
    - {{ posix }}automake          # [not win]
    - {{ posix }}automake-wrapper  # [win]
    - {{ posix }}pkg-config
    - {{ posix }}make
    - {{ posix }}coreutils         # [win]
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
    - libgomp  # [linux]
  run:
    - r-base

test:
  commands:
    - $R -e "library('kit')"           # [not win]
    - "\"%R%\" -e \"library('kit')\""  # [win]

about:
  home: https://CRAN.R-project.org/package=kit
  license: GPL-3.0-only
  summary: Basic functions, implemented in C, for large data manipulation. Fast vectorised ifelse()/nested if()/switch() functions, psum()/pprod() functions equivalent to pmin()/pmax() plus others which are missing from base R. Most of these functions are callable at C level.
  license_family: GPL3
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3

extra:
  recipe-maintainers:
    - conda-forge/r
    - mfansler

# Package: kit
# Type: Package
# Title: Data Manipulation Functions Implemented in C
# Version: 0.0.10
# Date: 2021-11-28
# Authors@R: c(person("Morgan", "Jacob", role = c("aut", "cre", "cph"), email = "morgan.emailbox@gmail.com"))
# Author: Morgan Jacob [aut, cre, cph]
# Maintainer: Morgan Jacob <morgan.emailbox@gmail.com>
# Description: Basic functions, implemented in C, for large data manipulation. Fast vectorised ifelse()/nested if()/switch() functions, psum()/pprod() functions equivalent to pmin()/pmax() plus others which are missing from base R. Most of these functions are callable at C level.
# License: GPL-3
# Depends: R (>= 3.1.0)
# Encoding: UTF-8
# BugReports: https://github.com/2005m/kit/issues
# NeedsCompilation: yes
# ByteCompile: TRUE
# Repository: CRAN
# Packaged: 2021-11-28 11:14:39 UTC; giuliabertuzzi
# Date/Publication: 2021-11-28 12:10:02 UTC
